# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocteams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repositorygit',
            options={'ordering': ['project_key', 'name']},
        ),
        migrations.RemoveField(
            model_name='jobjenkins',
            name='team',
        ),
        migrations.RemoveField(
            model_name='repositorygit',
            name='team',
        ),
        migrations.AddField(
            model_name='repositorygit',
            name='project_key',
            field=models.CharField(default='TESA', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='job_jenkins',
            field=models.ManyToManyField(to='vocteams.JobJenkins'),
        ),
        migrations.AddField(
            model_name='team',
            name='repository_git',
            field=models.ManyToManyField(to='vocteams.RepositoryGit'),
        ),
    ]
