# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocteams', '0006_auto_20171003_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_jenkins', models.ManyToManyField(to='vocteams.JobJenkins')),
                ('repository_git', models.ManyToManyField(to='vocteams.RepositoryGit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamVocento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('software_solution', models.ManyToManyField(to='vocteams.SoftwareSolution')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='job_jenkins',
        ),
        migrations.RemoveField(
            model_name='team',
            name='repository_git',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
