# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocteams', '0007_auto_20171017_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchgit',
            options={'ordering': ['name'], 'verbose_name_plural': 'Branches git'},
        ),
        migrations.AlterModelOptions(
            name='jobjenkins',
            options={'ordering': ['jenkins_server', 'name'], 'verbose_name_plural': 'Jobs jenkins'},
        ),
        migrations.AlterModelOptions(
            name='repositorygit',
            options={'ordering': ['project_key', 'name'], 'verbose_name_plural': 'Repositories git'},
        ),
        migrations.AlterModelOptions(
            name='softwaresolution',
            options={'ordering': ['name'], 'verbose_name_plural': 'Software solutions'},
        ),
        migrations.AlterModelOptions(
            name='teamvocento',
            options={'ordering': ['name'], 'verbose_name_plural': 'Teams vocento'},
        ),
    ]
