# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocteams', '0009_auto_20171122_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorygit',
            name='has_branch_develop',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='repositorygit',
            name='has_branch_master',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='repositorygit',
            name='branch_git',
            field=models.ManyToManyField(blank=True, to='vocteams.BranchGit'),
        ),
        migrations.AlterField(
            model_name='softwaresolution',
            name='job_jenkins',
            field=models.ManyToManyField(blank=True, to='vocteams.JobJenkins'),
        ),
        migrations.AlterField(
            model_name='softwaresolution',
            name='repository_git',
            field=models.ManyToManyField(blank=True, to='vocteams.RepositoryGit'),
        ),
        migrations.AlterField(
            model_name='teamvocento',
            name='software_solution',
            field=models.ManyToManyField(blank=True, to='vocteams.SoftwareSolution'),
        ),
    ]
