# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Application')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=120)),
                ('artifact_id', models.CharField(max_length=40)),
                ('repository_git', models.CharField(blank=True, max_length=120)),
                ('must_be_deployed', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Application')),
            ],
            options={
                'ordering': ['group_id', 'artifact_id'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Artifact')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactVersionChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('artifact_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ArtifactVersion')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StateApplicationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StateArtifactVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url_job_jenkins', models.CharField(blank=True, max_length=120)),
                ('name_package', models.CharField(default='zip', max_length=10)),
                ('unpack', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='state_artifact_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.StateArtifactVersion'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='technology_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TechnologyType'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='artifact_version',
            field=models.ManyToManyField(to='dashboard.ArtifactVersion'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='state_application_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.StateApplicationVersion'),
        ),
    ]
