# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170808_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateapplicationversion',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stateartifactversion',
            name='created',
        ),
    ]
