# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_environments_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationVersionEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ApplicationVersion')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Environments')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
