# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_applicationversionenvironment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationVersionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ApplicationVersion')),
                ('state_application_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.StateApplicationVersion')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='applicationversionenvironment',
            name='application_version',
        ),
        migrations.RemoveField(
            model_name='applicationversionenvironment',
            name='environment',
        ),
        migrations.DeleteModel(
            name='ApplicationVersionEnvironment',
        ),
        migrations.DeleteModel(
            name='Environments',
        ),
    ]
