# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20170823_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactversion',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
