# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_artifactversion_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationversion',
            name='build_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='build_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
