# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20171019_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationversion',
            name='build_number',
        ),
        migrations.RemoveField(
            model_name='artifactversion',
            name='build_number',
        ),
        migrations.AddField(
            model_name='application',
            name='build_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='build_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
