# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20171020_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationversion',
            name='created_from_branch',
            field=models.CharField(default='develop', max_length=40),
        ),
    ]
