# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_applicationversion_created_from_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactversion',
            name='build_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='repository_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
