# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20171110_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactversion',
            name='created_from_branch',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='applicationversion',
            name='created_from_branch',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
