# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180122_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationversion',
            name='email',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='email',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
