# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20180124_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactversionhistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='artifactversionhistory',
            name='author',
        ),
    ]
