# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20180124_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='pom_directory',
            field=models.CharField(default='.mvn', max_length=120),
        ),
    ]
