# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_artifact_pom_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
